export const portfolio = {
  estimate: {
    title: "estimate system",
    subtitle: "견적서",
    description: "옵션과 가격을 자유롭게 편집하고 저장할 수 있습니다. AWS S3 버킷에 저장해서 데이터를 다운로드, 업로드 해서 사용할 수 있게 처리했습니다. 묶음 옵션의 성립을 감지합니다. 오토컴플릿을 제작했습니다. 깔끔하게 이미지로 저장할 수 있습니다.",
    url: "https://estimatesystem.vercel.app",
    githubUrl: "",
    img: "",
  },
  ghibli: {
    title: "Ghibli",
    subtitle: "지브리",
    description: "지브리 데이터는 서버에, Graphql을 이용해 클라이언트와 데이터 주고 받기, 회원가입과 좋아요 감상평, MySQL을 AWS RDS에 호스팅, JsonWebToken Redis 방식에서 RDS 방식으로 변경",
    url: "https://ghibli.tccmd.site",
    githubUrl: "",
    img: "",
  },
  jobHomepage: {
    title: "가상의 회사 홈페이지",
    subtitle: "가상의 회사 홈페이지 ",
    description: "SEO를 위해 Nextjs 채택",
    url: "https://allrounder-vercel-tccmd.vercel.app",
    githubUrl: "",
    img: "",
  },
  dairies: {
    title: "Dairies",
    subtitle: "유업회사 홈페이지 클론",
    description: "Java, Spring Boot, MySQL",
    url: "https://allrounder-vercel-tccmd.vercel.app",
    githubUrl: "",
    img: "",
  },
  matterport: {
    title: "Matterport",
    subtitle: "3D 공간 촬영 후 편집과 작동을 SDK, API로 개발할 수 있다.",
    description: "JS, matterport sdk",
    url: "",
    githubUrl: "",
    img: "",
  },
  cudi: {
    title: "카페 앱",
    subtitle: "카페 앱",
    description: "Flutter",
    url: "",
    githubUrl: "",
    img: "",
  },
}